#
#   SETTINGS OVERVIEW
#
#   - Site Settings
#   - Color Schemes
#   - Typography
#   - Path Defaults
#   - SEO
#   - Favicons
#   - Sass
#   - disqus
#   - Analytics
#   - Social Media
#   - Gems & Excludes
#   - Compress
#

#   ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/


# Title and description of your site
title         : "YuManYu's Blog"
description   : 'This is our life.'
slogan        : 'YuManYu'



# Build settings
url           : 'https://wangyu16.github.io/YuManYu'
baseurl       : ''
markdown      : kramdown
highlighter   : rouge
permalink     : /:categories/:title/
encoding      : utf-8
destination   : _site
lang          : 'en'             # The language setting is used in /includes/header.html for html-settings



# Frontpage-Layout-Settings
posts_with_teaser_limit  : 1     # Define how many posts should be shown with headline, teaser, image, video
posts_list_limit         : 15    # Define how many posts should be shown in the list beneath the post(s)
excerpt_separator: <!--more-->   # Use <!--more--> in your posts to generate an excerpt and a teaser



#      ______      __              _____      __
#     / ____/___  / /___  _____   / ___/_____/ /_  ___  ____ ___  ___  _____
#    / /   / __ \/ / __ \/ ___/   \__ \/ ___/ __ \/ _ \/ __ `__ \/ _ \/ ___/
#   / /___/ /_/ / / /_/ / /      ___/ / /__/ / / /  __/ / / / / /  __(__  )
#   \____/\____/_/\____/_/      /____/\___/_/ /_/\___/_/ /_/ /_/\___/____/
#
#   Choose one of the following color schemes. Available color schemes:
#
#  - simplicity
#  - gloom_contrast
#  - glowfish
#  - legacy
#  - yule

color_scheme: simplicity



#     ______                                         __
#    /_  __/_  ______  ____  ____ __________ _____  / /_  __  __
#     / / / / / / __ \/ __ \/ __ `/ ___/ __ `/ __ \/ __ \/ / / /
#    / / / /_/ / /_/ / /_/ / /_/ / /  / /_/ / /_/ / / / / /_/ /
#   /_/  \__, / .___/\____/\__, /_/   \__,_/ .___/_/ /_/\__, /
#       /____/_/          /____/          /_/          /____/
#

#   Choose one of the following font combinations:
#
#   import is necessary to import the font from google
#   the settings for the fonts are used in /assets/css/simplicity.scss
font:
  import: 'Source+Code+Pro|Source+Sans+Pro:400,400italic,700,700italic'
  import: 'Lora|Noto+Sans+TC|Noto+Serif+TC'
#  import: 'Titillium+Web:400,400italic,700,700italic'
#  import: 'Roboto:400,400italic,700,700italic|Roboto+Mono'
#  import: 'Merriweather:400,400italic,700,700italic'
#  import: 'Arvo:400,400italic,700,700italic'
#  import: 'Gentium+Basic:400,400italic,700,700italic'
#  import: 'Fira+Sans:400,400italic,700,700italic|Fira+Mono'
  font-family-serif         : 'Lora, "Noto Serif TC", "Times New Roman", serif;'
  font-family-sans-serif    : '"Source Sans Pro", "Noto Sans TC", "Neue Helvetica", Arial, serif;'
  base-font-family          : 'Lora, "Noto Serif TC", "Times New Roman", serif;'
  font-family-monospace     : '"Source Code Pro", "Courier New", Monaco, monospace;'
  header-font-family        : '"Source Sans Pro", "Noto Sans TC", "Neue Helvetica", Arial, serif;'

#   Choose a modular scale.
#   What is a modular scale?
#   Read this › http://alistapart.com/article/more-meaningful-typography

modular_scale: modular_scale_1em
# modular_scale: modular_scale_ratio_1_125




#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: ''        # an empty string here means all files in the project
      type: 'pages'
    values:
      layout: page      # Set default layout to page
      show_meta: false  # Hide metadata for all pages
      comments: false
      author: 'YuManYu'     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: page      # Set default layout to page
      show_meta: true   # Show metadata for all posts
      comments: false
      author: 'YuManYu'     # Default author for posts



#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_site_verification   : 'Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ'
# bing_webmastertools_id   : ''
# alexa_verify_id          : ''



#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#        ____  _
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  )
#    /_____/_/____/\__, /\__,_/____/
#                    /_/
#
# used in _includes/comments

# disqus_shortname:


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/_4_footer_scripts

# google_analytics_tracking_id:



#    _____            _       __   __  ___         ___
#   / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#   \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#  ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
# /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
# If you have social media-profiles put your username here.
# Facebook and Twitter will be used in includes/_1_head.html
# To inject some meta-data other services will be used in
# _/includes/_4_footer.html.

socialmedia:
    #youtube: PhlowMedia
    github: wangyu16
    twitter: fishdream82
    # facebook: phlow.media
    # soundcloud: phlow
    # tumblr: motizen
    # instagram: phlowmedia
    # rss: # Full URL needed



#      ______                           ______          __          __
#     / ____/__  ____ ___       __     / ____/  _______/ /_  ______/ /__  _____
#    / / __/ _ \/ __ `__ \   __/ /_   / __/ | |/_/ ___/ / / / / __  / _ \/ ___/
#   / /_/ /  __/ / / / / /  /_  __/  / /____>  </ /__/ / /_/ / /_/ /  __(__  )
#   \____/\___/_/ /_/ /_/    /_/    /_____/_/|_|\___/_/\__,_/\__,_/\___/____/
plugins:
    - jekyll-gist
    - jekyll-sitemap
    - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md
    - vendor

#      ______
#     / ____/___  ____ ___  ____  ________  __________
#    / /   / __ \/ __ `__ \/ __ \/ ___/ _ \/ ___/ ___/
#   / /___/ /_/ / / / / / / /_/ / /  /  __(__  |__  )
#   \____/\____/_/ /_/ /_/ .___/_/   \___/____/____/
#                       /_/
#
# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings : all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]
